### ISSUE TITLE
Could some setup information be provided

### ISSUE THREAD

**Issue by blackholegalaxy** [anordby/gitlab-registry-cicd-cleanup#1]
Thanks for your script!

Is it possible for you to provide some basic setup and run information. We are not ruby guys and we don't want to mess with images by doing hazardous stuff.

**Comment by anordby** [comment]
I added some more information in TODO and the script. Does it solve this issue for you?

**Comment by blackholegalaxy** [comment]
Yes it does :) Thank you :)
