### ISSUE TITLE
readme: description of logic missing

### ISSUE THREAD

**Issue by glensc** [anordby/gitlab-registry-cicd-cleanup#2]
readme doesn't contain information what does the script do. i.e what is actually cleaned up.

for starters, just copy your own post?
- https://gitlab.com/gitlab-org/gitlab-ce/issues/25322#note_123229336

**Comment by anordby** [comment]
Ok I added more info to the README. Better? Anything else you miss?

**Comment by anordby** [comment]
The README was a bit of an afterthought, but of course should be helpful. Let me know if the script was useful for you after all.

**Comment by glensc** [comment]
I actually have the solution which satisfies me:
- https://gitlab.com/gitlab-org/gitlab-ce/issues/25322#note_92937283

But your approach is interesting indeed.

Plus i have gitlab hook in place to delete images on MR merge:
- https://github.com/glensc/gitlab-registry-cleanup-hook

**Comment by anordby** [comment]
Ok. May I close this issue?
